package com.example.step;

/**
 * The BuildConfig class is automatically generated by the Android build system.
 * This is a manual implementation for development purposes.
 */
public final class BuildConfig {
    public static final boolean DEBUG = true;
    public static final String APPLICATION_ID = "com.example.step";
    public static final String BUILD_TYPE = "debug";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
} 